# 1.0 Import libraries

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

# 2.0 Data load

In [3]:
df = pd.read_csv('/content/drive/MyDrive/lmf/data/2026_09_27_data_delivery_of_breeding_grasses_for_gwas_requested_by_claudia/gas_clean_complete_subsets_1234561h_2026_09_26.csv')
df.head(2)

,subset,no,requisitioner,id_lab,id,tax_order,family,genus,species,tax_name,...,ch4_ml_g_ndf_digested_24h,methane_intensity,tddm,information_remarks_1,information_remarks_2,gas_remarks_1,gas_remarks_2,digest_remarks_1,digest_remarks_2,delete
0,1,#REF!,LMF,F25-0017,Hohenheimer-Heustandard,Forage,Forage,Hohenheimer,Heustandard,Hohenheimer Heustandard,...,0,95.43754089,34.82973831,Standar,NaN,NaN,NaN,NaN,NaN,no
1,1,#REF!,LMF,F25-0017,Hohenheimer-Heustandard,Forage,Forage,Hohenheimer,Heustandard,Hohenheimer Heustandard,...,0,89.75200777,36.19469912,Standar,NaN,NaN,NaN,NaN,NaN,no

# 3.0 Formating GAS

In [4]:
df.functional_group.unique()

array(['Forage', 'Herbaceous_legumes', 'Shrub_Trees', nan, 'Grass',
       'Concentrate', 'Green Meal', 'Compound feed'], dtype=object)

In [5]:
df.requisitioner.unique()

array(['LMF', 'Genetic_bank', 'Breeding', 'Benchmark', 'LMF-invivo',
       'Isabel Molina', 'Mauricio Sotelo',
       'Jacobo Arango/Alejandro Montoya',
       'Jacobo Arango/ Alejandro Montoya', nan, 'ISABEL MOLINA',
       ' ISABEL MOLINA/ EXP Camaras In vivo ',
       'JACOBO ARANGO/ ALEJANDRO MONTOYA', 'JUAN CARDOSO'], dtype=object)

In [6]:
df1 = df[df['functional_group'] == 'Grass']

In [7]:
df2 = df1[df1['requisitioner'].isin(['Breeding', 'Benchmark'])]

In [8]:
df3 = df2[['subset','no','requisitioner','id_lab','id','tax_name','functional_group',
           'batch','run','replication', 'net_gas_8h_ml','net_gas_24h_ml',
           'gas_ml_g_dm_incubated_24h',  'tddm','part_fact','ch4_percentage_in_gas_8h',
       'ch4_percentage_in_gas_24h', 'ch4_ml_g_dm_incubated_24h', 'methane_intensity', 'ch4_ml_g_ndf_digested_24h'
       ]]
df3 = df3.copy()

cols = [ 'net_gas_8h_ml','net_gas_24h_ml',
           'gas_ml_g_dm_incubated_24h',  'tddm','part_fact','ch4_percentage_in_gas_8h',
       'ch4_percentage_in_gas_24h', 'ch4_ml_g_dm_incubated_24h', 'methane_intensity', 'ch4_ml_g_ndf_digested_24h']

df3[cols] = df3[cols].apply(pd.to_numeric, errors='coerce')
df3[cols] = df3[cols].round(2)

In [9]:
df3.tail()

,subset,no,requisitioner,id_lab,id,tax_name,functional_group,batch,run,replication,net_gas_8h_ml,net_gas_24h_ml,gas_ml_g_dm_incubated_24h,tddm,part_fact,ch4_percentage_in_gas_8h,ch4_percentage_in_gas_24h,ch4_ml_g_dm_incubated_24h,methane_intensity,ch4_ml_g_ndf_digested_24h
10147,6,1824,Breeding,F26-3070,CIAT-CIAT-6780,Urochloa interespecific,Grass,103,3,2,44.17,96.51,202.66,54.14,2.67,14.3,15.33,31.07,57.39,0.41
10148,6,1825,Breeding,F26-3071,CIAT-GP-3207,Urochloa interespecific,Grass,103,3,1,45.17,99.51,206.58,55.20,2.67,15.0,15.98,33.02,59.82,0.50
10149,6,1826,Breeding,F26-3071,CIAT-GP-3207,Urochloa interespecific,Grass,103,3,2,45.17,99.01,205.46,52.21,2.54,15.1,16.08,33.04,63.28,0.59
10150,6,1827,Breeding,F26-3072,CIAT-Mavuno,Urochloa interespecific,Grass,103,3,1,41.17,86.51,180.95,55.28,3.06,14.2,15.09,27.31,49.40,0.55
10151,6,1828,Breeding,F26-3072,CIAT-Mavuno,Urochloa interespecific,Grass,103,3,2,41.17,84.51,176.83,53.97,3.05,13.9,14.98,26.48,49.08,0.58

In [10]:
df3.to_csv('/content/drive/MyDrive/lmf/output/2026_09_27_data_delivery_of_breeding_grasses_for_gwas_requested_by_claudia/gas_breeding_complete_2026_09_27.csv', index=None)

# 4.0 Formating Nutrition

In [11]:
nu = pd.read_csv('/content/drive/MyDrive/lmf/data/2026_09_27_data_delivery_of_breeding_grasses_for_gwas_requested_by_claudia/nutrition_complete_subsets_1234561h_2026_09_26.csv')
nu.head(2)

,subset,no,requisitioner,id_lab,id,tax_order,family,genus,species,tax_name,functional_group,set_ciat,dm_percentage,ash_dm,om_percentage,pc_percentage_dm,adf_percentage_dm,ndf_percentage_dm
0,1,1.0,Genetic_bank,F24-3416,CIAT-705,Fabales,Fabaceae,Indigofera,suffruticosa,Indigofera suffruticosa,Shrub_Trees,1,91.930807,12.725691,87.274309,33.010522,28.489614,45.210329
1,1,2.0,Genetic_bank,F24-3416,CIAT-705,Fabales,Fabaceae,Indigofera,suffruticosa,Indigofera suffruticosa,Shrub_Trees,1,92.010000,12.629062,87.370938,33.010522,27.612657,45.235119

In [12]:
nu.functional_group.unique()

array(['Shrub_Trees', 'Herbaceous_legumes', 'Grass', 'Forage',
       'Concentrate', nan, 'Green Meal', 'Compound feed'], dtype=object)

In [13]:
nu1 = nu[nu['functional_group'] == 'Grass']

In [14]:
nu2 = nu1[nu1['requisitioner'].isin(['Breeding', 'Benchmark'])]
nu2.tail(2)

,subset,no,requisitioner,id_lab,id,tax_order,family,genus,species,tax_name,functional_group,set_ciat,dm_percentage,ash_dm,om_percentage,pc_percentage_dm,adf_percentage_dm,ndf_percentage_dm
3290,1h,11.0,Breeding,F26-1079,CIAT-MulatoII-Exc-E,Poales,Poaceae,Urochloa,interespecific,Urochloa interespecific,Grass,NaN,92.5,NaN,NaN,NaN,NaN,NaN
3291,1h,12.0,Breeding,F26-1079,CIAT-MulatoII-Exc-E,Poales,Poaceae,Urochloa,interespecific,Urochloa interespecific,Grass,NaN,92.5,NaN,NaN,NaN,NaN,NaN

In [15]:
cols = ['dm_percentage', 'ash_dm', 'om_percentage', 'pc_percentage_dm','adf_percentage_dm', 'ndf_percentage_dm']
nu2[cols] = nu2[cols].round(2)

/tmp/ipykernel_11348/1946393332.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nu2[cols] = nu2[cols].round(2)

In [16]:
nu2.to_csv('/content/drive/MyDrive/lmf/output/2026_09_27_data_delivery_of_breeding_grasses_for_gwas_requested_by_claudia/nutrition_breeding_complete_2026_09_27.csv', index=None)